### ISSUE TITLE
query pattern?

### ISSUE THREAD

**Issue by muratcorlu** [venturachrisdev/djurl#6]
In the readme file, there is an example for usage of djurl with a `query` pattern:

```
url('/blog/search/:query', SearchResultsView, name="search")
```

But, as I see, there is no pattern named `query`, isn't it?

**Comment by venturachrisdev** [comment]
Hi, Murat! At first, I just wrote that as an example about how powerful Djurl can be. There wasn't a pattern named `:query`, but now I'm thinking in integrate it in *v0.2.0* as a generalized form of `:slug` so I'll keep this opened until I add this pattern. Thanks for the feedback!
